
spring.application.name=portfolio

# GitHub API Config
github.token=${GITHUB_TOKEN}
github.username=kartavynirwel-code

# Cache TTL - 10 minutes
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=600s
spring.cache.type=caffeine

# Server
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false
